version: "3.3"

services:
  bot:
    image: maanex/freestuffbot
    environment:
      NODE_ENV: "dev"
      BOT_TOKEN: "token"
      BOT_ID: "756183898156957850"
      MONGO_URL: "mongodb://host.docker.internal:27017/admin"
      FREESTUFF_KEY: "verysecret"
      SENTRY_DSN: ""
    # restart_policy:
    #   condition: any
    #   delay: 5s
    #   max_attempts: 3
    #   window: 30s
